spring.application.name=alb-core-service
server.port=8080

logging.level.org.springframework.web=INFO
logging.level.com.capstone.alb=DEBUG
sentinel.api.base-url=http://localhost:8000
sentinel.collection.bad-confidence-threshold=0.75
sentinel.collection.review-confidence-threshold=0.45
