spring.application.name=alb-core-service
server.port=8080
server.node.id=local-node

logging.level.org.springframework.web=INFO
logging.level.com.capstone.alb=DEBUG
logging.level.com.capstone.alb.service=DEBUG
logging.level.com.capstone.alb.strategy=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.mvc.async.request-timeout=5000
sentinel.api.base-url=http://localhost:8000
